---
title: isError
description: ""
---

```ts
function isError<K, T>(error, code): error is T
```

Returns true if the `error` matches an error thrown by quais
 that matches the error `code`.

 In TypeScript environments, this can be used to check that `error`
 matches an quaisError type, which means the expected properties will
 be set.

## Type parameters

| Type parameter |
| :------ |
| `K` *extends* [`ErrorCode`](/content/type-aliases/ErrorCode.mdx) |
| `T` *extends* 
  \| [`UnknownError`](/content/interfaces/UnknownError.mdx)
  \| [`InvalidArgumentError`](/content/interfaces/InvalidArgumentError.mdx)
  \| [`BadDataError`](/content/interfaces/BadDataError.mdx)
  \| [`NotImplementedError`](/content/interfaces/NotImplementedError.mdx)
  \| [`UnsupportedOperationError`](/content/interfaces/UnsupportedOperationError.mdx)
  \| [`NetworkError`](/content/interfaces/NetworkError.mdx)
  \| [`ServerError`](/content/interfaces/ServerError.mdx)
  \| [`TimeoutError`](/content/interfaces/TimeoutError.mdx)
  \| [`CancelledError`](/content/interfaces/CancelledError.mdx)
  \| [`BufferOverrunError`](/content/interfaces/BufferOverrunError.mdx)
  \| [`NumericFaultError`](/content/interfaces/NumericFaultError.mdx)
  \| [`MissingArgumentError`](/content/interfaces/MissingArgumentError.mdx)
  \| [`UnexpectedArgumentError`](/content/interfaces/UnexpectedArgumentError.mdx)
  \| [`CallExceptionError`](/content/interfaces/CallExceptionError.mdx)
  \| [`InsufficientFundsError`](/content/interfaces/InsufficientFundsError.mdx)
  \| [`NonceExpiredError`](/content/interfaces/NonceExpiredError.mdx)
  \| [`ReplacementUnderpricedError`](/content/interfaces/ReplacementUnderpricedError.mdx)
  \| [`TransactionReplacedError`](/content/interfaces/TransactionReplacedError.mdx)
  \| [`ActionRejectedError`](/content/interfaces/ActionRejectedError.mdx) |

## Parameters

| Parameter | Type |
| :------ | :------ |
| `error` | `any` |
| `code` | `K` |

## Returns

`error is T`

## See

[ErrorCodes](api:ErrorCode)

## Example

```ts
   try {
     // code....
   } catch (e) {
     if (isError(e, "CALL_EXCEPTION")) {
         // The Type Guard has validated this object
         console.log(e.data);
     }
   }
 ```

## Source

[src.ts/utils/errors.ts:657](https://github.com/dominant-strategies/quais-6.js/blob/3f482dd134064d41657ff7dc9ba8162f741c9c83/src.ts/utils/errors.ts#L657)
